<?php

namespace AppBundle\Repository;

use AppBundle\Entity\QueenBee;
use Doctrine\ORM\EntityRepository;

/**
 * OtherBeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OtherBeeRepository extends EntityRepository
{
    /**
     * @param QueenBee $queenBee
     *
     * @return mixed
     */
    public function refillBees(QueenBee $queenBee)
    {
        $qb = $this->createQueryBuilder('ob');

        $qb
            ->update('AppBundle:OtherBee', 'ob')
            ->set('ob.remainingLifespan', 'ob.maxLifespan')
            ->where($qb->expr()->eq('ob.queenBee', ':qb'))
            ->setParameter('qb', $queenBee)
        ;

        return $qb->getQuery()->execute();
    }
}
