<?php

namespace AppBundle\Repository;

use AppBundle\Entity\QueenBee;
use Doctrine\ORM\EntityRepository;

/**
 * QueenBeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueenBeeRepository extends EntityRepository
{
    /**
     * @param QueenBee $queenBee
     *
     * @return mixed
     */
    public function refillBees(QueenBee $queenBee)
    {
        $qb = $this->createQueryBuilder('qb');

        $qb
            ->update('AppBundle:QueenBee', 'qb')
            ->set('qb.remainingLifespan', 'qb.maxLifespan')
            ->where($qb->expr()->eq('qb', ':qb'))
            ->setParameter('qb', $queenBee)
        ;

        return $qb->getQuery()->execute();
    }
}
